#!/usr/bin/env python3
"""Generate a bounded MCP tool summary from the authoritative registry."""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from mcp_main.win.mcp import server  # noqa: E402
from onshape_browser_mode import semantics as browser_semantics  # noqa: E402

OUTPUT_PATH = REPO_ROOT / "docs" / "generated" / "TOOL_REFERENCE.md"


def capability(name: str) -> str:
    if name.startswith("docs_"):
        return "project_docs"
    if name.startswith("fs_"):
        return "featurescript"
    if name in {
        "onshape_api_list_tags",
        "onshape_api_search",
        "onshape_api_endpoint",
        "onshape_api_schema",
        "onshape_api_auth",
        "onshape_api_error_codes",
    }:
        return "rest_reference"
    if name.startswith("onshape_"):
        return "rest_operations"
    if name.startswith("browser_"):
        return "browser"
    return "other"


def compact(text: str, limit: int = 180) -> str:
    value = " ".join(text.split()).replace("|", "\\|")
    if len(value) <= limit:
        return value
    return value[: limit - 3].rstrip() + "..."


def bool_text(value: Any) -> str:
    return "yes" if value is True else "no"


def semantic_label(name: str) -> str:
    if not name.startswith("browser_"):
        return "-"
    metadata = browser_semantics.semantic_metadata(name)
    if metadata is None:
        return "`unclassified`"
    level = metadata["semanticLevel"]
    semantic_name = metadata["semanticName"]
    return f"`{level} {semantic_name}`" if level else f"`{semantic_name}`"


def tool_row(tool: dict[str, Any]) -> str:
    name = tool["name"]
    schema = tool.get("inputSchema") or {}
    properties = schema.get("properties") or {}
    required = schema.get("required") or []
    cost = tool.get("cost") or {}
    annotations = tool.get("annotations") or {}
    mutating = bool(cost.get("mutating", not annotations.get("readOnlyHint", False)))
    dry_run = "dry_run" in properties
    confirmation = "confirm_mutation" in properties
    network = str(cost.get("network", "unspecified"))
    api_max = cost.get("max_api_requests", cost.get("max_requests", 0))
    required_text = ", ".join(f"`{item}`" for item in required) or "-"
    safety = (
        f"network={network}; api_max={api_max}; mutating={bool_text(mutating)}; "
        f"dry_run={bool_text(dry_run)}; confirm={bool_text(confirmation)}"
    )
    return (
        f"| `{name}` | `{capability(name)}` | {semantic_label(name)} | {required_text} | {safety} | "
        f"{compact(str(tool.get('description', '')))} |"
    )


def render() -> str:
    tools = list(server.TOOLS)
    tool_names = [tool.get("name") for tool in tools]
    handler_names = set(server.HANDLERS)
    if any(not isinstance(name, str) or not name for name in tool_names):
        raise ValueError("every registered tool must have a non-empty string name")
    duplicates = sorted(name for name, count in Counter(tool_names).items() if count > 1)
    if duplicates:
        raise ValueError(f"duplicate registered tool names: {duplicates}")
    missing_handlers = sorted(set(tool_names) - handler_names)
    orphan_handlers = sorted(handler_names - set(tool_names))
    if missing_handlers or orphan_handlers:
        raise ValueError(
            f"tool/handler mismatch: missing_handlers={missing_handlers}, "
            f"orphan_handlers={orphan_handlers}"
        )

    counts = Counter(capability(name) for name in tool_names)
    semantic_counts = Counter()
    for name in tool_names:
        if not name.startswith("browser_"):
            continue
        metadata = browser_semantics.semantic_metadata(name)
        key = (
            "unclassified"
            if metadata is None
            else str(metadata["semanticLevel"] or metadata["semanticName"])
        )
        semantic_counts[key] += 1
    lines = [
        "# Generated MCP tool reference",
        "",
        "> Generated by `onshape_docs/scripts/build_tool_reference.py` from the",
        "> registered `mcp_main.win.mcp.server.TOOLS` and `HANDLERS`. Do not edit this file",
        "> manually. Runtime MCP schemas remain authoritative for complete arguments.",
        "",
        "## Summary",
        "",
        f"- Registered tools: **{len(tools)}**",
        f"- Server: `{server.SERVER_NAME}` `{server.SERVER_VERSION}`",
        f"- MCP protocol: `{server.PROTOCOL_VERSION}`",
        "- Capability counts: "
        + ", ".join(f"`{name}`={counts[name]}" for name in sorted(counts)),
        "- Browser semantic counts: "
        + ", ".join(f"`{name}`={semantic_counts[name]}" for name in sorted(semantic_counts)),
        "",
        "## Safety interpretation",
        "",
        "- `network=offline` means zero live Onshape REST calls; most entries are local, while an explicitly described reference refresh may use public zero-quota sources.",
        "- `network=browser` consumes zero REST quota but a real UI action may mutate cloud data.",
        "- Live REST operations remain disabled unless `LIVE_API_ENABLED` is explicitly enabled.",
        "- `api_max` is registered metadata, not permission to spend requests.",
        "- `confirm=yes` means the public schema exposes `confirm_mutation`; callers must still follow host approval.",
        "- Browser semantic classification is optional discovery guidance; it is not a registration, permission, or execution gate.",
    ]
    for group in sorted(counts):
        lines.extend([
            "",
            f"## Capability: {group}",
            "",
            "| Tool | Capability | Optional semantic classification | Required arguments | Registered safety/cost | Intent |",
            "|---|---|---|---|---|---|",
        ])
        lines.extend(
            tool_row(tool)
            for tool in sorted(tools, key=lambda item: item["name"])
            if capability(tool["name"]) == group
        )
    lines.extend([
        "",
        "## Authority",
        "",
        "Use the runtime `tools/list` schema for complete argument types, defaults, and",
        "annotations. Public behavior is implemented by the matching registered handler.",
        "Update schemas and handlers together, then regenerate this file and run the MCP",
        "protocol tests.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT_PATH.is_file():
            print(f"missing generated tool reference: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(f"stale generated tool reference: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        print(f"Tool reference is current: {OUTPUT_PATH}")
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
