#!/usr/bin/env python3
"""Vendor Onshape developer documentation (auth + error handling) into reference/raw/onshape-api-docs/.

These are public GitHub Pages documents (onshape-public.github.io), fetched with
plain HTTP - they consume no Onshape API token quota. They cover the two gaps
the OpenAPI spec leaves for real operations:

  errors  - HTTP response codes and recommended next steps
  limits  - API rate limits and annual call limits
  oauth   - the OAuth2 authorization-code workflow
  apikeys - creating and using API keys (Basic auth)

Afterwards run onshape_docs/scripts/build_onshape_api_docs_index.py to parse them into JSON.
"""

from __future__ import annotations

import argparse
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from onshape_docs.query.source_digest import text_sha256  # noqa: E402

DOCS_DIR = ROOT / "reference" / "raw" / "onshape-api-docs"

PAGES = {
    "errors": "https://onshape-public.github.io/docs/api-adv/errors/",
    "limits": "https://onshape-public.github.io/docs/auth/limits/",
    "oauth": "https://onshape-public.github.io/docs/auth/oauth/",
    "apikeys": "https://onshape-public.github.io/docs/auth/apikeys/",
}


def write_readme() -> None:
    lines = [
        "# Vendored Onshape developer docs (auth + error handling)",
        "",
        "Generated by `python3 onshape_docs/scripts/fetch_onshape_api_docs.py`. These pages",
        "are from the public Onshape developer documentation at",
        "`https://onshape-public.github.io/docs/` (© Onshape). They are fetched",
        "with plain HTTP and consume no Onshape API token quota. They fill the",
        "two gaps the OpenAPI spec leaves for real operations: the OAuth2 /",
        "API-key authentication procedure and HTTP error / rate-limit semantics.",
        "",
        "Parsed into `api_docs.json` by `onshape_docs/scripts/build_onshape_api_docs_index.py`",
        "(each page's sha256 is recorded there for staleness checks).",
    ]
    (DOCS_DIR / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--quiet", action="store_true", help="only print failures")
    args = parser.parse_args()

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    failed = 0
    for page, url in PAGES.items():
        try:
            with urllib.request.urlopen(url, timeout=120) as response:
                data = response.read()
        except Exception as error:
            failed += 1
            print(f"  FAIL {url}: {error}", file=sys.stderr)
            continue
        target = DOCS_DIR / f"{page}.html"
        target.write_bytes(data)
        if not args.quiet:
            print(f"  ok   {page}.html ({len(data)} bytes) sha256={text_sha256(target)}")
    write_readme()
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
